name: Deploy to Production

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Generar Archivo
        run: 
          echo "Archivo prueba, hola" >> test.log
      
      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: test.log