name: Deploy to Production

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    env:
      NAME: OSCAR MORENO

    steps:
      - name: Hola mundo
        run: echo "Hola mundo desde el primer job ${{ env.NAME }}"

      - name: Working dir
        run: ls -al

      - name: Action
        uses: actions/checkout@v4

      - name: Working dir after action
        id: step3
        run: echo "my_variable=Hola oscar" >> $GITHUB_OUTPUT
      
      - name: Show variable
        run: echo "The variable is ${{ steps.step3.outputs.my_variable }}"

  second_job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run: echo "Hola mundo desde el segundo job ${{ github.ref}}"
